apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: stg

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: webserver.stg.koronet
configMapGenerator:
- name: koronet-config
  behavior: merge
  literals:
  - ENVIRONMENT=stg
  - DATABASE=koronet_stg_db
